name: Deploy to Crates.io

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      
      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      
      - name: Verify version matches tag
        run: |
          CARGO_VERSION=$(grep '^version' Cargo.toml | head -1 | cut -d'"' -f2)
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Cargo.toml version: '$CARGO_VERSION'"
          echo "Git tag version: '$TAG_VERSION'"
          echo "GITHUB_REF: '$GITHUB_REF'"
          [ "$CARGO_VERSION" = "$TAG_VERSION" ] || exit 1
      
      - name: Lint and test
        run: |
          cargo clippy -- -D warnings
          cargo test --lib --bins
          cargo build --release
      
      - name: Dry run publish
        run: cargo publish --dry-run
      
      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}